// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "api.proto" (package "api", syntax proto3)
// tslint:disable
import { None } from "./messages";
import { UnaryStreamRequest } from "./messages";
import { StreamResponses } from "./messages";
import { StreamRequests } from "./messages";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service api.api
 */
export const api = new ServiceType("api.api", [
    { name: "Stream", serverStreaming: true, options: {}, I: StreamRequests, O: StreamResponses },
    { name: "StreamRequest", options: {}, I: UnaryStreamRequest, O: None }
]);
